import { db } from "./db";
import { dayContent, badges } from "@shared/schema";

async function seed() {
  console.log("🌱 Seeding database...");

  // Seed badges
  console.log("Creating badges...");
  const badgeData = [
    {
      name: "First Steps",
      description: "Completed Day 1: Idea Explosion",
      icon: "🎯",
      triggerType: "day_completed",
      triggerValue: 1,
    },
    {
      name: "Visionary",
      description: "Completed Clarifier Phase (Days 1-7)",
      icon: "🔍",
      triggerType: "day_completed",
      triggerValue: 7,
    },
    {
      name: "Architect",
      description: "Completed Blueprint Architect Phase (Days 8-14)",
      icon: "📐",
      triggerType: "day_completed",
      triggerValue: 14,
    },
    {
      name: "Maker",
      description: "Completed Maker Mode (Day 15)",
      icon: "⚡",
      triggerType: "day_completed",
      triggerValue: 15,
    },
    {
      name: "Builder",
      description: "Completed MVP Builder Phase (Days 16-23)",
      icon: "🏗️",
      triggerType: "day_completed",
      triggerValue: 23,
    },
    {
      name: "Perfectionist",
      description: "Completed Refinement Specialist Phase (Days 24-27)",
      icon: "✨",
      triggerType: "day_completed",
      triggerValue: 27,
    },
    {
      name: "Product Creator",
      description: "Completed Product Creator Phase (Days 28-29)",
      icon: "🎨",
      triggerType: "day_completed",
      triggerValue: 29,
    },
    {
      name: "The Finisher",
      description: "Completed all 30 days!",
      icon: "🏆",
      triggerType: "day_completed",
      triggerValue: 30,
    },
    {
      name: "On Fire!",
      description: "7-day streak",
      icon: "🔥",
      triggerType: "streak",
      triggerValue: 7,
    },
    {
      name: "Unstoppable",
      description: "14-day streak",
      icon: "⚡",
      triggerType: "streak",
      triggerValue: 14,
    },
  ];

  for (const badge of badgeData) {
    await db.insert(badges).values(badge).onConflictDoNothing();
  }

  // Seed day content (30 days)
  console.log("Creating day content...");
  const dayContentData = [
    // PHASE 1: Clarifier (Days 1-7)
    {
      day: 1,
      title: "Your Million Dollar Idea",
      description: "Use AI to generate 28 SaaS ideas in 5 minutes",
      phase: "Week 1: Planning & Idea",
      videoUrl: null,
      aiTaskType: "suggestion",
      aiTaskTitle: "AI-Generated SaaS Ideas",
      aiTaskDescription: "Let AI generate 28 SaaS ideas based on your interests, skills, and market trends. Select the one that resonates most with you.",
      suggestions: JSON.stringify([
        { title: "AI Writing Assistant", desc: "Help content creators write better, faster" },
        { title: "Project Management Tool", desc: "Simplified project tracking for small teams" },
        { title: "Customer Feedback Platform", desc: "Collect and analyze customer insights" },
      ]),
      template: null,
      microDecisionQuestion: "Which area excites you most?",
      microDecisionOptions: JSON.stringify(["B2B", "B2C", "Developer Tools", "E-commerce"]),
      reflectionQuestion: "What problem do you want to solve and why does it matter to you?",
      outcome: "A shortlist of 3-5 SaaS ideas validated by AI, ready for deeper evaluation",
      completionMessage: "Most people never get past 'someday I'll start.' You just generated 28 ideas and picked your favorites. You're already ahead of 90% of people who talk about building a business. Tomorrow, we find out which one has legs.",
      xpReward: 100,
    },
    {
      day: 2,
      title: "Will People Pay For This?",
      description: "Identify the top 3 pain points and validate market demand",
      phase: "Week 1: Planning & Idea",
      videoUrl: null,
      aiTaskType: "suggestion",
      aiTaskTitle: "Market Research & Competitor Analysis",
      aiTaskDescription: "AI analyzes your chosen idea against existing solutions, market size, and potential opportunities.",
      suggestions: null,
      template: null,
      microDecisionQuestion: "What's your primary competitive advantage?",
      microDecisionOptions: JSON.stringify(["Better UX", "Lower Price", "Unique Feature", "Niche Focus"]),
      reflectionQuestion: "What makes your solution different from existing alternatives?",
      outcome: "One validated SaaS idea with 1-3 specific, painful problems it solves for customers",
      completionMessage: "The hardest decision is behind you. You picked ONE idea and identified the exact pains it solves. That's what separates builders from dreamers - making a choice and committing. Now we turn these pain points into a real product.",
      xpReward: 100,
    },
    {
      day: 3,
      title: "Core Features & Your USP",
      description: "AI analyzes competitors and generates your feature list",
      phase: "Week 1: Planning & Idea",
      videoUrl: null,
      aiTaskType: "suggestion",
      aiTaskTitle: "Feature Generation & Competitor Analysis",
      aiTaskDescription: "AI generates core features based on your pain points, analyzes competitors to find shared must-have features, and suggests unique USP features to differentiate you.",
      suggestions: null,
      template: null,
      microDecisionQuestion: "Which features are most important to you?",
      microDecisionOptions: JSON.stringify(["Core problem-solving features", "Competitive must-haves", "Unique differentiators", "All of them"]),
      reflectionQuestion: "What one unique feature will make customers choose you over competitors?",
      outcome: "A complete feature list with core features, competitive must-haves, and your unique USP features",
      completionMessage: "You know what beats a 'perfect' feature list? One that you can actually build. You just defined your core features, what competitors have, and what makes you different. Most founders never get this specific. Tomorrow: we turn these features into a buildable roadmap.",
      xpReward: 100,
      estimatedMinutes: 5,
    },
    {
      day: 4,
      title: "Deciding on Your MVP Roadmap",
      description: "AI prioritizes which features to build first",
      phase: "Week 1: Planning & Idea",
      videoUrl: null,
      aiTaskType: "suggestion",
      aiTaskTitle: "MVP Roadmap Generator",
      aiTaskDescription: "AI analyzes your features and creates a prioritized roadmap showing what MUST be built for MVP vs what can wait until after launch.",
      suggestions: null,
      template: null,
      microDecisionQuestion: "What's your MVP philosophy?",
      microDecisionOptions: JSON.stringify(["Launch fast, iterate later", "Build it right the first time", "Balanced approach", "Maximum features"]),
      reflectionQuestion: "What's the absolute minimum feature set that delivers real value to customers?",
      outcome: "A prioritized MVP roadmap with build order and estimated timelines",
      completionMessage: "Your AI toolkit is ready. You now have a clear roadmap of what to build first and what can wait. Most founders build the wrong things first and waste months. You won't. Tomorrow: we set up the tools that'll help you build this thing.",
      xpReward: 100,
      estimatedMinutes: 5,
    },
    {
      day: 5,
      title: "AI Tech Stack",
      description: "Set up your AI-powered development tools",
      phase: "Week 1: Planning & Idea",
      videoUrl: null,
      aiTaskType: "setup",
      aiTaskTitle: "Tech Stack Setup",
      aiTaskDescription: "Sign up for Replit (your AI-powered dev environment) and Claude Code (your AI coding assistant). These are the tools that'll 10x your development speed.",
      suggestions: null,
      template: null,
      microDecisionQuestion: "Have you used AI coding tools before?",
      microDecisionOptions: JSON.stringify(["Never", "A little", "Regularly", "I'm a pro"]),
      reflectionQuestion: "What's holding you back from building right now?",
      outcome: "Replit and Claude Code accounts set up and ready to build",
      completionMessage: "Your AI toolkit is ready. You now have the superpowers that would've taken weeks to set up manually. Tomorrow we use these tools to create your PRD. The fun part starts now.",
      xpReward: 100,
      estimatedMinutes: 5,
    },
    {
      day: 6,
      title: "Summarizing EVERYTHING, Analyzing It & Creating the PRD",
      description: "AI generates your complete Product Requirements Document",
      phase: "Week 1: Planning & Idea",
      videoUrl: null,
      aiTaskType: "template",
      aiTaskTitle: "PRD Generation",
      aiTaskDescription: "AI summarizes everything from Days 1-5 and creates a professional Product Requirements Document with feature specs, user stories, and technical requirements.",
      suggestions: null,
      template: null,
      microDecisionQuestion: "How detailed should your PRD be?",
      microDecisionOptions: JSON.stringify(["Brief overview", "Standard detail", "Very detailed", "Everything included"]),
      reflectionQuestion: "Looking at everything you've defined, what excites you most about building this?",
      outcome: "A complete, professional PRD ready to guide development",
      completionMessage: "You have a PRD. A real Product Requirements Document that tells you exactly what to build and what to ignore. Most founders skip this and wonder why they're still coding 6 months later with nothing to show. You're different. Tomorrow: you start building.",
      xpReward: 100,
      estimatedMinutes: 5,
    },
    {
      day: 7,
      title: "Entering the PRD and Building the Software",
      description: "Get your PRD into Replit and start building with AI",
      phase: "Week 1: Planning & Idea",
      videoUrl: null,
      aiTaskType: "setup",
      aiTaskTitle: "Start Building in Replit",
      aiTaskDescription: "Copy your PRD into Replit, set up your project with Claude Code, and start building your first MVP feature.",
      suggestions: null,
      template: null,
      microDecisionQuestion: "Which feature will you build first?",
      microDecisionOptions: JSON.stringify(["Authentication", "Main core feature", "Database setup", "Landing page"]),
      reflectionQuestion: "What will it feel like when you see your first feature working?",
      outcome: "Your PRD in Replit and your first build session complete",
      completionMessage: "Week 1 done. 7 days of clarity and planning. While others are still 'thinking about it,' you have a validated idea, a clear plan, the tools set up, and you've started building. This is what separates builders from dreamers. Next week: we build the MVP.",
      xpReward: 100,
      estimatedMinutes: 5,
    },

    // PHASE 2: Blueprint Architect (Days 8-14)
    {
      day: 8,
      title: "User Flow Mapping",
      description: "AI designs your core user journey",
      phase: "Blueprint Architect",
      videoUrl: null,
      aiTaskType: "template",
      aiTaskTitle: "User Flow Template",
      aiTaskDescription: "AI maps out the step-by-step user journey from landing to conversion.",
      suggestions: null,
      template: null,
      microDecisionQuestion: "What's your primary user action?",
      microDecisionOptions: JSON.stringify(["Sign up", "Create project", "Upload file", "Make payment"]),
      reflectionQuestion: "What's the shortest path to user success in your app?",
      outcome: "A clear map of how customers will move through your product from first visit to paying customer",
      xpReward: 100,
    },
    {
      day: 9,
      title: "Database Schema",
      description: "Let AI design your database structure",
      phase: "Blueprint Architect",
      videoUrl: null,
      aiTaskType: "template",
      aiTaskTitle: "Database Schema Generator",
      aiTaskDescription: "AI creates an optimized database schema based on your features.",
      suggestions: null,
      template: null,
      microDecisionQuestion: "Which database type?",
      microDecisionOptions: JSON.stringify(["PostgreSQL", "MySQL", "MongoDB", "Firebase"]),
      reflectionQuestion: "What data relationships are critical to your product?",
      outcome: "A blueprint for how your product will store and organize customer data",
      xpReward: 100,
    },
    {
      day: 10,
      title: "API Architecture",
      description: "AI generates your API endpoint structure",
      phase: "Blueprint Architect",
      videoUrl: null,
      aiTaskType: "template",
      aiTaskTitle: "API Blueprint",
      aiTaskDescription: "AI designs RESTful API endpoints for your core features.",
      suggestions: null,
      template: null,
      microDecisionQuestion: "API architecture preference?",
      microDecisionOptions: JSON.stringify(["REST", "GraphQL", "tRPC", "gRPC"]),
      reflectionQuestion: "What data operations are most critical to your app?",
      outcome: "A plan for how your product's features will communicate and work together behind the scenes",
      xpReward: 100,
    },
    {
      day: 11,
      title: "Authentication Strategy",
      description: "AI suggests auth flows for your product",
      phase: "Blueprint Architect",
      videoUrl: null,
      aiTaskType: "suggestion",
      aiTaskTitle: "Authentication Design",
      aiTaskDescription: "AI recommends authentication methods based on your user needs.",
      suggestions: null,
      template: null,
      microDecisionQuestion: "Primary auth method?",
      microDecisionOptions: JSON.stringify(["Email/Password", "Social OAuth", "Magic Link", "SSO"]),
      reflectionQuestion: "How can you make signup as frictionless as possible?",
      outcome: "A decision on how customers will sign up and log in with minimal friction",
      xpReward: 100,
    },
    {
      day: 12,
      title: "Wireframe Generation",
      description: "AI creates low-fidelity wireframes",
      phase: "Blueprint Architect",
      videoUrl: null,
      aiTaskType: "template",
      aiTaskTitle: "Wireframe Templates",
      aiTaskDescription: "AI generates wireframe layouts for your key screens.",
      suggestions: null,
      template: null,
      microDecisionQuestion: "Layout priority?",
      microDecisionOptions: JSON.stringify(["Dashboard-first", "Landing page-first", "Onboarding-first", "Settings-first"]),
      reflectionQuestion: "What screen will users spend the most time on?",
      outcome: "Simple sketches showing what every key screen in your product will look like",
      xpReward: 100,
    },
    {
      day: 13,
      title: "Tech Stack Selection",
      description: "Let AI recommend the perfect tech stack",
      phase: "Blueprint Architect",
      videoUrl: null,
      aiTaskType: "suggestion",
      aiTaskTitle: "Tech Stack Recommendations",
      aiTaskDescription: "AI suggests frameworks and tools based on your requirements and skill level.",
      suggestions: null,
      template: null,
      microDecisionQuestion: "Development experience?",
      microDecisionOptions: JSON.stringify(["Beginner", "Intermediate", "Advanced", "Expert"]),
      reflectionQuestion: "What technologies are you most comfortable with?",
      outcome: "The tools and technologies your developer will use to build your product",
      xpReward: 100,
    },
    {
      day: 14,
      title: "Integration Planning",
      description: "AI maps out third-party integrations",
      phase: "Blueprint Architect",
      videoUrl: null,
      aiTaskType: "suggestion",
      aiTaskTitle: "Integration Roadmap",
      aiTaskDescription: "AI identifies essential third-party services for payments, email, analytics, etc.",
      suggestions: null,
      template: null,
      microDecisionQuestion: "Top priority integration?",
      microDecisionOptions: JSON.stringify(["Payment", "Email", "Analytics", "Storage"]),
      reflectionQuestion: "Which external services are absolutely necessary for your MVP?",
      outcome: "A list of required third-party integrations with setup priorities",
      xpReward: 100,
    },

    // PHASE 3: Maker Mode (Day 15)
    {
      day: 15,
      title: "Build Day - MVP Sprint",
      description: "AI-assisted development: Set up your project and build core features",
      phase: "Maker Mode",
      videoUrl: null,
      aiTaskType: "setup",
      aiTaskTitle: "Project Setup & Core Build",
      aiTaskDescription: "Today you build! Use AI to scaffold your project, set up authentication, database, and implement 1-2 core features.",
      suggestions: null,
      template: null,
      microDecisionQuestion: "What will you build first?",
      microDecisionOptions: JSON.stringify(["Auth system", "Main feature", "Database", "UI framework"]),
      reflectionQuestion: "What did you accomplish today? What surprised you?",
      outcome: "A working early version of your product where users can sign up and use your main feature",
      xpReward: 200,
    },

    // PHASE 4: MVP Builder (Days 16-23)
    {
      day: 16,
      title: "Landing Page",
      description: "AI generates landing page copy and structure",
      phase: "MVP Builder",
      videoUrl: null,
      aiTaskType: "template",
      aiTaskTitle: "Landing Page Template",
      aiTaskDescription: "AI creates conversion-optimized landing page sections.",
      suggestions: null,
      template: null,
      microDecisionQuestion: "Primary CTA?",
      microDecisionOptions: JSON.stringify(["Sign Up", "Book Demo", "Start Free Trial", "Watch Video"]),
      reflectionQuestion: "What's the one thing visitors must understand in 5 seconds?",
      outcome: "A conversion-optimized landing page with compelling copy and clear CTAs",
      xpReward: 100,
    },
    {
      day: 17,
      title: "Onboarding Flow",
      description: "Design user onboarding with AI guidance",
      phase: "MVP Builder",
      videoUrl: null,
      aiTaskType: "suggestion",
      aiTaskTitle: "Onboarding Sequence",
      aiTaskDescription: "AI designs a smooth onboarding flow to activate new users.",
      suggestions: null,
      template: null,
      microDecisionQuestion: "Onboarding style?",
      microDecisionOptions: JSON.stringify(["Interactive tutorial", "Quick setup wizard", "Video walkthrough", "Self-guided"]),
      reflectionQuestion: "What's the 'aha moment' in your product?",
      outcome: "A smooth onboarding flow that gets users to their first win quickly",
      xpReward: 100,
    },
    {
      day: 18,
      title: "Core Feature #1",
      description: "Build your main feature with AI pair programming",
      phase: "MVP Builder",
      videoUrl: null,
      aiTaskType: "setup",
      aiTaskTitle: "Feature Implementation",
      aiTaskDescription: "AI helps you implement your primary feature with code suggestions.",
      suggestions: null,
      template: null,
      microDecisionQuestion: "Implementation approach?",
      microDecisionOptions: JSON.stringify(["Build from scratch", "Use template", "Clone similar feature", "Hybrid"]),
      reflectionQuestion: "What's the smallest version of this feature that works?",
      outcome: "Your main product feature is built and ready for customers to use",
      xpReward: 100,
    },
    {
      day: 19,
      title: "Core Feature #2",
      description: "Implement your second key feature",
      phase: "MVP Builder",
      videoUrl: null,
      aiTaskType: "setup",
      aiTaskTitle: "Second Feature Build",
      aiTaskDescription: "Continue building with AI-generated code and debugging help.",
      suggestions: null,
      template: null,
      microDecisionQuestion: "Feature complexity?",
      microDecisionOptions: JSON.stringify(["Simple", "Moderate", "Complex", "Very complex"]),
      reflectionQuestion: "How does this feature complement your first one?",
      outcome: "Your second key feature is live, creating a more complete product experience",
      xpReward: 100,
    },
    {
      day: 20,
      title: "Payment Integration",
      description: "Set up Stripe with AI configuration",
      phase: "MVP Builder",
      videoUrl: null,
      aiTaskType: "setup",
      aiTaskTitle: "Payment Setup Guide",
      aiTaskDescription: "AI walks you through Stripe integration step-by-step.",
      suggestions: null,
      template: null,
      microDecisionQuestion: "Payment approach?",
      microDecisionOptions: JSON.stringify(["Subscription only", "One-time + subscription", "Usage-based", "Freemium"]),
      reflectionQuestion: "What pricing tier will you launch with?",
      outcome: "Your product can now accept payments and charge customers for subscriptions",
      xpReward: 100,
    },
    {
      day: 21,
      title: "Email Automation",
      description: "Configure transactional emails with AI",
      phase: "MVP Builder",
      videoUrl: null,
      aiTaskType: "template",
      aiTaskTitle: "Email Templates",
      aiTaskDescription: "AI generates welcome emails, notifications, and drip campaign templates.",
      suggestions: null,
      template: null,
      microDecisionQuestion: "Email service?",
      microDecisionOptions: JSON.stringify(["SendGrid", "Postmark", "AWS SES", "Resend"]),
      reflectionQuestion: "What's the most important email to get right?",
      outcome: "Automated emails set up to welcome new users and keep them engaged",
      xpReward: 100,
    },
    {
      day: 22,
      title: "Analytics Setup",
      description: "Implement tracking with AI recommendations",
      phase: "MVP Builder",
      videoUrl: null,
      aiTaskType: "setup",
      aiTaskTitle: "Analytics Implementation",
      aiTaskDescription: "AI suggests key metrics to track and helps implement analytics.",
      suggestions: null,
      template: null,
      microDecisionQuestion: "Analytics tool?",
      microDecisionOptions: JSON.stringify(["Google Analytics", "Mixpanel", "PostHog", "Plausible"]),
      reflectionQuestion: "What's your north star metric?",
      outcome: "Tracking in place so you can see what users do and how many convert to paying customers",
      xpReward: 100,
    },
    {
      day: 23,
      title: "Error Handling",
      description: "AI reviews and improves error handling",
      phase: "MVP Builder",
      videoUrl: null,
      aiTaskType: "suggestion",
      aiTaskTitle: "Error Prevention",
      aiTaskDescription: "AI identifies potential errors and suggests defensive code patterns.",
      suggestions: null,
      template: null,
      microDecisionQuestion: "Error monitoring?",
      microDecisionOptions: JSON.stringify(["Sentry", "LogRocket", "Bugsnag", "Built-in logging"]),
      reflectionQuestion: "What errors would be most catastrophic for users?",
      outcome: "Systems in place to catch and fix problems before they affect your customers",
      xpReward: 100,
    },

    // PHASE 5: Refinement Specialist (Days 24-27)
    {
      day: 24,
      title: "Performance Optimization",
      description: "AI analyzes and optimizes performance",
      phase: "Refinement Specialist",
      videoUrl: null,
      aiTaskType: "suggestion",
      aiTaskTitle: "Performance Audit",
      aiTaskDescription: "AI identifies bottlenecks and suggests optimizations.",
      suggestions: null,
      template: null,
      microDecisionQuestion: "Priority optimization?",
      microDecisionOptions: JSON.stringify(["Page load speed", "API response time", "Database queries", "Bundle size"]),
      reflectionQuestion: "Where do users experience the most friction?",
      outcome: "Your product loads faster and feels smoother for a better customer experience",
      xpReward: 100,
    },
    {
      day: 25,
      title: "UX Polish",
      description: "AI suggests UX improvements",
      phase: "Refinement Specialist",
      videoUrl: null,
      aiTaskType: "suggestion",
      aiTaskTitle: "UX Enhancement",
      aiTaskDescription: "AI reviews your interface and recommends usability improvements.",
      suggestions: null,
      template: null,
      microDecisionQuestion: "UX priority?",
      microDecisionOptions: JSON.stringify(["Mobile responsive", "Accessibility", "Loading states", "Error messages"]),
      reflectionQuestion: "What would make your app feel more polished?",
      outcome: "A more professional-looking product that works great on mobile and desktop",
      xpReward: 100,
    },
    {
      day: 26,
      title: "Security Audit",
      description: "AI-powered security review",
      phase: "Refinement Specialist",
      videoUrl: null,
      aiTaskType: "suggestion",
      aiTaskTitle: "Security Checklist",
      aiTaskDescription: "AI audits your code for common security vulnerabilities.",
      suggestions: null,
      template: null,
      microDecisionQuestion: "Security focus?",
      microDecisionOptions: JSON.stringify(["Data encryption", "Auth security", "API security", "Input validation"]),
      reflectionQuestion: "What sensitive data needs the most protection?",
      outcome: "Customer data is protected and your product meets basic security standards",
      xpReward: 100,
    },
    {
      day: 27,
      title: "Testing Strategy",
      description: "AI generates test cases",
      phase: "Refinement Specialist",
      videoUrl: null,
      aiTaskType: "template",
      aiTaskTitle: "Test Suite Generator",
      aiTaskDescription: "AI creates unit and integration test templates.",
      suggestions: null,
      template: null,
      microDecisionQuestion: "Testing priority?",
      microDecisionOptions: JSON.stringify(["Unit tests", "Integration tests", "E2E tests", "Manual QA"]),
      reflectionQuestion: "What functionality absolutely cannot break?",
      outcome: "Confidence that your core features work reliably and won't break during launch",
      xpReward: 100,
    },

    // PHASE 6: Product Creator (Days 28-29)
    {
      day: 28,
      title: "Launch Checklist",
      description: "AI creates your pre-launch checklist",
      phase: "Product Creator",
      videoUrl: null,
      aiTaskType: "template",
      aiTaskTitle: "Launch Preparation",
      aiTaskDescription: "AI generates a comprehensive launch checklist.",
      suggestions: null,
      template: null,
      microDecisionQuestion: "Launch platform?",
      microDecisionOptions: JSON.stringify(["Product Hunt", "Hacker News", "Reddit", "LinkedIn"]),
      reflectionQuestion: "What needs to be perfect before you launch?",
      outcome: "A complete pre-launch checklist with all tasks and platform strategy defined",
      xpReward: 100,
    },
    {
      day: 29,
      title: "Marketing Content",
      description: "AI writes launch announcement content",
      phase: "Product Creator",
      videoUrl: null,
      aiTaskType: "template",
      aiTaskTitle: "Launch Content Pack",
      aiTaskDescription: "AI generates social posts, Product Hunt description, and announcement email.",
      suggestions: null,
      template: null,
      microDecisionQuestion: "Marketing angle?",
      microDecisionOptions: JSON.stringify(["Problem-focused", "Solution-focused", "Story-focused", "Feature-focused"]),
      reflectionQuestion: "What makes your product worth sharing?",
      outcome: "Launch content ready: social posts, Product Hunt copy, and announcement emails",
      xpReward: 100,
    },

    // PHASE 7: The Finisher (Day 30)
    {
      day: 30,
      title: "Launch Day!",
      description: "You did it! Launch your MVP to the world",
      phase: "The Finisher",
      videoUrl: null,
      aiTaskType: "setup",
      aiTaskTitle: "Final Launch Sequence",
      aiTaskDescription: "Today you launch! AI helps with deployment checklist and post-launch monitoring.",
      suggestions: null,
      template: null,
      microDecisionQuestion: "Launch feeling?",
      microDecisionOptions: JSON.stringify(["Excited", "Nervous", "Confident", "All of the above!"]),
      reflectionQuestion: "What did you learn most during this 30-day journey? What's next?",
      outcome: "Your SaaS MVP is live and available to the world!",
      completionMessage: "You did it. 30 days ago, this was just an idea. Today, it's live. Most people never make it past day 3. You shipped. That makes you a founder. Now go get your first customer.",
      xpReward: 300,
    },
  ];

  for (const day of dayContentData) {
    await db.insert(dayContent).values(day).onConflictDoUpdate({
      target: dayContent.day,
      set: {
        title: day.title,
        description: day.description,
        phase: day.phase,
        videoUrl: day.videoUrl,
        aiTaskType: day.aiTaskType,
        aiTaskTitle: day.aiTaskTitle,
        aiTaskDescription: day.aiTaskDescription,
        suggestions: day.suggestions,
        template: day.template,
        microDecisionQuestion: day.microDecisionQuestion,
        microDecisionOptions: day.microDecisionOptions,
        reflectionQuestion: day.reflectionQuestion,
        tip: (day as any).tip || null,
        lesson: (day as any).lesson || null,
        outcome: day.outcome,
        completionMessage: day.completionMessage,
        estimatedMinutes: day.estimatedMinutes,
        xpReward: day.xpReward,
        updatedAt: new Date(),
      },
    });
  }

  console.log("✅ Seeding complete!");
  process.exit(0);
}

seed().catch((error) => {
  console.error("❌ Seeding failed:", error);
  process.exit(1);
});
