import { db } from "./db";
import { dayContent, badges } from "@shared/schema";

async function seed() {
  console.log("🌱 Seeding database...");

  // Seed badges
  console.log("Creating badges...");
  const badgeData = [
    {
      name: "First Steps",
      description: "Completed Day 1: Idea Explosion",
      icon: "🎯",
      triggerType: "day_completed",
      triggerValue: 1,
    },
    {
      name: "Visionary",
      description: "Completed Clarifier Phase (Days 1-7)",
      icon: "🔍",
      triggerType: "day_completed",
      triggerValue: 7,
    },
    {
      name: "Architect",
      description: "Completed Blueprint Architect Phase (Days 8-14)",
      icon: "📐",
      triggerType: "day_completed",
      triggerValue: 14,
    },
    {
      name: "Maker",
      description: "Completed Maker Mode (Day 15)",
      icon: "⚡",
      triggerType: "day_completed",
      triggerValue: 15,
    },
    {
      name: "Builder",
      description: "Completed MVP Builder Phase (Days 16-23)",
      icon: "🏗️",
      triggerType: "day_completed",
      triggerValue: 23,
    },
    {
      name: "Perfectionist",
      description: "Completed Refinement Specialist Phase (Days 24-27)",
      icon: "✨",
      triggerType: "day_completed",
      triggerValue: 27,
    },
    {
      name: "Product Creator",
      description: "Completed Product Creator Phase (Days 28-29)",
      icon: "🎨",
      triggerType: "day_completed",
      triggerValue: 29,
    },
    {
      name: "The Finisher",
      description: "Completed all 30 days!",
      icon: "🏆",
      triggerType: "day_completed",
      triggerValue: 30,
    },
    {
      name: "On Fire!",
      description: "7-day streak",
      icon: "🔥",
      triggerType: "streak",
      triggerValue: 7,
    },
    {
      name: "Unstoppable",
      description: "14-day streak",
      icon: "⚡",
      triggerType: "streak",
      triggerValue: 14,
    },
  ];

  for (const badge of badgeData) {
    await db.insert(badges).values(badge).onConflictDoNothing();
  }

  // Seed day content (30 days)
  console.log("Creating day content...");
  const dayContentData = [
    // PHASE 1: Clarifier (Days 1-7)
    {
      day: 1,
      title: "Idea Explosion",
      description: "Use AI to generate 30 unique SaaS ideas in 5 minutes",
      phase: "Clarifier",
      videoUrl: null,
      aiTaskType: "suggestion",
      aiTaskTitle: "AI-Generated SaaS Ideas",
      aiTaskDescription: "Let AI generate 30 SaaS ideas based on your interests, skills, and market trends. Select the one that resonates most with you.",
      suggestions: JSON.stringify([
        { title: "AI Writing Assistant", desc: "Help content creators write better, faster" },
        { title: "Project Management Tool", desc: "Simplified project tracking for small teams" },
        { title: "Customer Feedback Platform", desc: "Collect and analyze customer insights" },
      ]),
      template: null,
      microDecisionQuestion: "Which area excites you most?",
      microDecisionOptions: JSON.stringify(["B2B", "B2C", "Developer Tools", "E-commerce"]),
      reflectionQuestion: "What problem do you want to solve and why does it matter to you?",
      outcome: "A shortlist of 3-5 SaaS ideas validated by AI, ready for deeper evaluation",
      xpReward: 100,
    },
    {
      day: 2,
      title: "Market Validation",
      description: "Validate your idea with AI-powered market research",
      phase: "Clarifier",
      videoUrl: null,
      aiTaskType: "suggestion",
      aiTaskTitle: "Market Research & Competitor Analysis",
      aiTaskDescription: "AI analyzes your chosen idea against existing solutions, market size, and potential opportunities.",
      suggestions: null,
      template: null,
      microDecisionQuestion: "What's your primary competitive advantage?",
      microDecisionOptions: JSON.stringify(["Better UX", "Lower Price", "Unique Feature", "Niche Focus"]),
      reflectionQuestion: "What makes your solution different from existing alternatives?",
      outcome: "One validated SaaS idea with clear competitive advantages and market opportunity",
      xpReward: 100,
    },
    {
      day: 3,
      title: "Target Audience",
      description: "Define your perfect customer with AI personas",
      phase: "Clarifier",
      videoUrl: null,
      aiTaskType: "suggestion",
      aiTaskTitle: "Customer Persona Generator",
      aiTaskDescription: "AI creates detailed customer personas including demographics, pain points, and buying behaviors.",
      suggestions: null,
      template: null,
      microDecisionQuestion: "Who will use your product first?",
      microDecisionOptions: JSON.stringify(["Small Business Owners", "Freelancers", "Enterprise Teams", "Consumers"]),
      reflectionQuestion: "What pain point keeps your ideal customer up at night?",
      outcome: "A detailed customer persona with demographics, pain points, and buying behaviors",
      xpReward: 100,
    },
    {
      day: 4,
      title: "Value Proposition",
      description: "Craft a compelling one-liner with AI copywriting",
      phase: "Clarifier",
      videoUrl: null,
      aiTaskType: "template",
      aiTaskTitle: "Value Proposition Template",
      aiTaskDescription: "AI generates multiple value proposition variations you can refine.",
      suggestions: null,
      template: "For [target customer] who [need statement], [product name] is a [product category] that [key benefit]. Unlike [competitors], our product [unique differentiator].",
      microDecisionQuestion: "What's your main benefit focus?",
      microDecisionOptions: JSON.stringify(["Save Time", "Save Money", "Reduce Complexity", "Increase Revenue"]),
      reflectionQuestion: "If you could only say one thing about your product, what would it be?",
      outcome: "A compelling value proposition that clearly communicates your unique benefit",
      xpReward: 100,
    },
    {
      day: 5,
      title: "Feature Prioritization",
      description: "Use AI to prioritize your MVP features",
      phase: "Clarifier",
      videoUrl: null,
      aiTaskType: "suggestion",
      aiTaskTitle: "AI Feature Prioritization",
      aiTaskDescription: "AI analyzes your product concept and suggests which features matter most for your MVP.",
      suggestions: null,
      template: null,
      microDecisionQuestion: "What's your MVP philosophy?",
      microDecisionOptions: JSON.stringify(["Minimal viable", "Feature-rich", "Design-first", "Data-driven"]),
      reflectionQuestion: "What's the absolute minimum feature set that delivers value?",
      outcome: "A prioritized feature list with must-haves, nice-to-haves, and features to cut",
      xpReward: 100,
    },
    {
      day: 6,
      title: "Revenue Model",
      description: "Let AI suggest pricing strategies for your SaaS",
      phase: "Clarifier",
      videoUrl: null,
      aiTaskType: "suggestion",
      aiTaskTitle: "Pricing Strategy Generator",
      aiTaskDescription: "AI recommends pricing models based on your product, market, and competitors.",
      suggestions: null,
      template: null,
      microDecisionQuestion: "Which pricing model fits best?",
      microDecisionOptions: JSON.stringify(["Subscription", "Freemium", "Pay-per-use", "One-time"]),
      reflectionQuestion: "What would your ideal customer be willing to pay?",
      outcome: "A clear pricing strategy with model selection and initial price points",
      xpReward: 100,
    },
    {
      day: 7,
      title: "Product Name & Brand",
      description: "Generate memorable product names with AI",
      phase: "Clarifier",
      videoUrl: null,
      aiTaskType: "suggestion",
      aiTaskTitle: "Brand Name Generator",
      aiTaskDescription: "AI creates catchy, memorable product names aligned with your vision.",
      suggestions: null,
      template: null,
      microDecisionQuestion: "What brand style resonates with you?",
      microDecisionOptions: JSON.stringify(["Professional", "Playful", "Modern", "Classic"]),
      reflectionQuestion: "What feeling do you want your brand to evoke?",
      outcome: "A memorable product name and brand identity that resonates with your target audience",
      xpReward: 100,
    },

    // PHASE 2: Blueprint Architect (Days 8-14)
    {
      day: 8,
      title: "User Flow Mapping",
      description: "AI designs your core user journey",
      phase: "Blueprint Architect",
      videoUrl: null,
      aiTaskType: "template",
      aiTaskTitle: "User Flow Template",
      aiTaskDescription: "AI maps out the step-by-step user journey from landing to conversion.",
      suggestions: null,
      template: null,
      microDecisionQuestion: "What's your primary user action?",
      microDecisionOptions: JSON.stringify(["Sign up", "Create project", "Upload file", "Make payment"]),
      reflectionQuestion: "What's the shortest path to user success in your app?",
      outcome: "A complete user flow diagram from landing to key conversion points",
      xpReward: 100,
    },
    {
      day: 9,
      title: "Database Schema",
      description: "Let AI design your database structure",
      phase: "Blueprint Architect",
      videoUrl: null,
      aiTaskType: "template",
      aiTaskTitle: "Database Schema Generator",
      aiTaskDescription: "AI creates an optimized database schema based on your features.",
      suggestions: null,
      template: null,
      microDecisionQuestion: "Which database type?",
      microDecisionOptions: JSON.stringify(["PostgreSQL", "MySQL", "MongoDB", "Firebase"]),
      reflectionQuestion: "What data relationships are critical to your product?",
      outcome: "An optimized database schema with all necessary tables and relationships defined",
      xpReward: 100,
    },
    {
      day: 10,
      title: "API Architecture",
      description: "AI generates your API endpoint structure",
      phase: "Blueprint Architect",
      videoUrl: null,
      aiTaskType: "template",
      aiTaskTitle: "API Blueprint",
      aiTaskDescription: "AI designs RESTful API endpoints for your core features.",
      suggestions: null,
      template: null,
      microDecisionQuestion: "API architecture preference?",
      microDecisionOptions: JSON.stringify(["REST", "GraphQL", "tRPC", "gRPC"]),
      reflectionQuestion: "What data operations are most critical to your app?",
      outcome: "A complete API endpoint structure with routes, methods, and data contracts",
      xpReward: 100,
    },
    {
      day: 11,
      title: "Authentication Strategy",
      description: "AI suggests auth flows for your product",
      phase: "Blueprint Architect",
      videoUrl: null,
      aiTaskType: "suggestion",
      aiTaskTitle: "Authentication Design",
      aiTaskDescription: "AI recommends authentication methods based on your user needs.",
      suggestions: null,
      template: null,
      microDecisionQuestion: "Primary auth method?",
      microDecisionOptions: JSON.stringify(["Email/Password", "Social OAuth", "Magic Link", "SSO"]),
      reflectionQuestion: "How can you make signup as frictionless as possible?",
      outcome: "A secure authentication strategy with chosen methods and implementation plan",
      xpReward: 100,
    },
    {
      day: 12,
      title: "Wireframe Generation",
      description: "AI creates low-fidelity wireframes",
      phase: "Blueprint Architect",
      videoUrl: null,
      aiTaskType: "template",
      aiTaskTitle: "Wireframe Templates",
      aiTaskDescription: "AI generates wireframe layouts for your key screens.",
      suggestions: null,
      template: null,
      microDecisionQuestion: "Layout priority?",
      microDecisionOptions: JSON.stringify(["Dashboard-first", "Landing page-first", "Onboarding-first", "Settings-first"]),
      reflectionQuestion: "What screen will users spend the most time on?",
      outcome: "Low-fidelity wireframes for all critical screens in your application",
      xpReward: 100,
    },
    {
      day: 13,
      title: "Tech Stack Selection",
      description: "Let AI recommend the perfect tech stack",
      phase: "Blueprint Architect",
      videoUrl: null,
      aiTaskType: "suggestion",
      aiTaskTitle: "Tech Stack Recommendations",
      aiTaskDescription: "AI suggests frameworks and tools based on your requirements and skill level.",
      suggestions: null,
      template: null,
      microDecisionQuestion: "Development experience?",
      microDecisionOptions: JSON.stringify(["Beginner", "Intermediate", "Advanced", "Expert"]),
      reflectionQuestion: "What technologies are you most comfortable with?",
      outcome: "A complete tech stack decision with frontend, backend, and infrastructure choices",
      xpReward: 100,
    },
    {
      day: 14,
      title: "Integration Planning",
      description: "AI maps out third-party integrations",
      phase: "Blueprint Architect",
      videoUrl: null,
      aiTaskType: "suggestion",
      aiTaskTitle: "Integration Roadmap",
      aiTaskDescription: "AI identifies essential third-party services for payments, email, analytics, etc.",
      suggestions: null,
      template: null,
      microDecisionQuestion: "Top priority integration?",
      microDecisionOptions: JSON.stringify(["Payment", "Email", "Analytics", "Storage"]),
      reflectionQuestion: "Which external services are absolutely necessary for your MVP?",
      outcome: "A list of required third-party integrations with setup priorities",
      xpReward: 100,
    },

    // PHASE 3: Maker Mode (Day 15)
    {
      day: 15,
      title: "Build Day - MVP Sprint",
      description: "AI-assisted development: Set up your project and build core features",
      phase: "Maker Mode",
      videoUrl: null,
      aiTaskType: "setup",
      aiTaskTitle: "Project Setup & Core Build",
      aiTaskDescription: "Today you build! Use AI to scaffold your project, set up authentication, database, and implement 1-2 core features.",
      suggestions: null,
      template: null,
      microDecisionQuestion: "What will you build first?",
      microDecisionOptions: JSON.stringify(["Auth system", "Main feature", "Database", "UI framework"]),
      reflectionQuestion: "What did you accomplish today? What surprised you?",
      outcome: "A working project foundation with authentication, database, and 1-2 core features implemented",
      xpReward: 200,
    },

    // PHASE 4: MVP Builder (Days 16-23)
    {
      day: 16,
      title: "Landing Page",
      description: "AI generates landing page copy and structure",
      phase: "MVP Builder",
      videoUrl: null,
      aiTaskType: "template",
      aiTaskTitle: "Landing Page Template",
      aiTaskDescription: "AI creates conversion-optimized landing page sections.",
      suggestions: null,
      template: null,
      microDecisionQuestion: "Primary CTA?",
      microDecisionOptions: JSON.stringify(["Sign Up", "Book Demo", "Start Free Trial", "Watch Video"]),
      reflectionQuestion: "What's the one thing visitors must understand in 5 seconds?",
      outcome: "A conversion-optimized landing page with compelling copy and clear CTAs",
      xpReward: 100,
    },
    {
      day: 17,
      title: "Onboarding Flow",
      description: "Design user onboarding with AI guidance",
      phase: "MVP Builder",
      videoUrl: null,
      aiTaskType: "suggestion",
      aiTaskTitle: "Onboarding Sequence",
      aiTaskDescription: "AI designs a smooth onboarding flow to activate new users.",
      suggestions: null,
      template: null,
      microDecisionQuestion: "Onboarding style?",
      microDecisionOptions: JSON.stringify(["Interactive tutorial", "Quick setup wizard", "Video walkthrough", "Self-guided"]),
      reflectionQuestion: "What's the 'aha moment' in your product?",
      outcome: "A smooth onboarding flow that gets users to their first win quickly",
      xpReward: 100,
    },
    {
      day: 18,
      title: "Core Feature #1",
      description: "Build your main feature with AI pair programming",
      phase: "MVP Builder",
      videoUrl: null,
      aiTaskType: "setup",
      aiTaskTitle: "Feature Implementation",
      aiTaskDescription: "AI helps you implement your primary feature with code suggestions.",
      suggestions: null,
      template: null,
      microDecisionQuestion: "Implementation approach?",
      microDecisionOptions: JSON.stringify(["Build from scratch", "Use template", "Clone similar feature", "Hybrid"]),
      reflectionQuestion: "What's the smallest version of this feature that works?",
      outcome: "Your primary feature fully implemented and functional",
      xpReward: 100,
    },
    {
      day: 19,
      title: "Core Feature #2",
      description: "Implement your second key feature",
      phase: "MVP Builder",
      videoUrl: null,
      aiTaskType: "setup",
      aiTaskTitle: "Second Feature Build",
      aiTaskDescription: "Continue building with AI-generated code and debugging help.",
      suggestions: null,
      template: null,
      microDecisionQuestion: "Feature complexity?",
      microDecisionOptions: JSON.stringify(["Simple", "Moderate", "Complex", "Very complex"]),
      reflectionQuestion: "How does this feature complement your first one?",
      outcome: "Your second key feature working and integrated with your first",
      xpReward: 100,
    },
    {
      day: 20,
      title: "Payment Integration",
      description: "Set up Stripe with AI configuration",
      phase: "MVP Builder",
      videoUrl: null,
      aiTaskType: "setup",
      aiTaskTitle: "Payment Setup Guide",
      aiTaskDescription: "AI walks you through Stripe integration step-by-step.",
      suggestions: null,
      template: null,
      microDecisionQuestion: "Payment approach?",
      microDecisionOptions: JSON.stringify(["Subscription only", "One-time + subscription", "Usage-based", "Freemium"]),
      reflectionQuestion: "What pricing tier will you launch with?",
      outcome: "Stripe integration complete with subscriptions and payment processing working",
      xpReward: 100,
    },
    {
      day: 21,
      title: "Email Automation",
      description: "Configure transactional emails with AI",
      phase: "MVP Builder",
      videoUrl: null,
      aiTaskType: "template",
      aiTaskTitle: "Email Templates",
      aiTaskDescription: "AI generates welcome emails, notifications, and drip campaign templates.",
      suggestions: null,
      template: null,
      microDecisionQuestion: "Email service?",
      microDecisionOptions: JSON.stringify(["SendGrid", "Postmark", "AWS SES", "Resend"]),
      reflectionQuestion: "What's the most important email to get right?",
      outcome: "Transactional emails configured with welcome messages and key notifications",
      xpReward: 100,
    },
    {
      day: 22,
      title: "Analytics Setup",
      description: "Implement tracking with AI recommendations",
      phase: "MVP Builder",
      videoUrl: null,
      aiTaskType: "setup",
      aiTaskTitle: "Analytics Implementation",
      aiTaskDescription: "AI suggests key metrics to track and helps implement analytics.",
      suggestions: null,
      template: null,
      microDecisionQuestion: "Analytics tool?",
      microDecisionOptions: JSON.stringify(["Google Analytics", "Mixpanel", "PostHog", "Plausible"]),
      reflectionQuestion: "What's your north star metric?",
      outcome: "Analytics tracking implemented for key user actions and conversion metrics",
      xpReward: 100,
    },
    {
      day: 23,
      title: "Error Handling",
      description: "AI reviews and improves error handling",
      phase: "MVP Builder",
      videoUrl: null,
      aiTaskType: "suggestion",
      aiTaskTitle: "Error Prevention",
      aiTaskDescription: "AI identifies potential errors and suggests defensive code patterns.",
      suggestions: null,
      template: null,
      microDecisionQuestion: "Error monitoring?",
      microDecisionOptions: JSON.stringify(["Sentry", "LogRocket", "Bugsnag", "Built-in logging"]),
      reflectionQuestion: "What errors would be most catastrophic for users?",
      outcome: "Comprehensive error handling and monitoring in place for critical paths",
      xpReward: 100,
    },

    // PHASE 5: Refinement Specialist (Days 24-27)
    {
      day: 24,
      title: "Performance Optimization",
      description: "AI analyzes and optimizes performance",
      phase: "Refinement Specialist",
      videoUrl: null,
      aiTaskType: "suggestion",
      aiTaskTitle: "Performance Audit",
      aiTaskDescription: "AI identifies bottlenecks and suggests optimizations.",
      suggestions: null,
      template: null,
      microDecisionQuestion: "Priority optimization?",
      microDecisionOptions: JSON.stringify(["Page load speed", "API response time", "Database queries", "Bundle size"]),
      reflectionQuestion: "Where do users experience the most friction?",
      outcome: "Key performance bottlenecks identified and optimized for better user experience",
      xpReward: 100,
    },
    {
      day: 25,
      title: "UX Polish",
      description: "AI suggests UX improvements",
      phase: "Refinement Specialist",
      videoUrl: null,
      aiTaskType: "suggestion",
      aiTaskTitle: "UX Enhancement",
      aiTaskDescription: "AI reviews your interface and recommends usability improvements.",
      suggestions: null,
      template: null,
      microDecisionQuestion: "UX priority?",
      microDecisionOptions: JSON.stringify(["Mobile responsive", "Accessibility", "Loading states", "Error messages"]),
      reflectionQuestion: "What would make your app feel more polished?",
      outcome: "Polished UX with improved responsiveness, loading states, and error messaging",
      xpReward: 100,
    },
    {
      day: 26,
      title: "Security Audit",
      description: "AI-powered security review",
      phase: "Refinement Specialist",
      videoUrl: null,
      aiTaskType: "suggestion",
      aiTaskTitle: "Security Checklist",
      aiTaskDescription: "AI audits your code for common security vulnerabilities.",
      suggestions: null,
      template: null,
      microDecisionQuestion: "Security focus?",
      microDecisionOptions: JSON.stringify(["Data encryption", "Auth security", "API security", "Input validation"]),
      reflectionQuestion: "What sensitive data needs the most protection?",
      outcome: "Security vulnerabilities identified and fixed with proper data protection in place",
      xpReward: 100,
    },
    {
      day: 27,
      title: "Testing Strategy",
      description: "AI generates test cases",
      phase: "Refinement Specialist",
      videoUrl: null,
      aiTaskType: "template",
      aiTaskTitle: "Test Suite Generator",
      aiTaskDescription: "AI creates unit and integration test templates.",
      suggestions: null,
      template: null,
      microDecisionQuestion: "Testing priority?",
      microDecisionOptions: JSON.stringify(["Unit tests", "Integration tests", "E2E tests", "Manual QA"]),
      reflectionQuestion: "What functionality absolutely cannot break?",
      outcome: "Test coverage for critical functionality ensuring reliability before launch",
      xpReward: 100,
    },

    // PHASE 6: Product Creator (Days 28-29)
    {
      day: 28,
      title: "Launch Checklist",
      description: "AI creates your pre-launch checklist",
      phase: "Product Creator",
      videoUrl: null,
      aiTaskType: "template",
      aiTaskTitle: "Launch Preparation",
      aiTaskDescription: "AI generates a comprehensive launch checklist.",
      suggestions: null,
      template: null,
      microDecisionQuestion: "Launch platform?",
      microDecisionOptions: JSON.stringify(["Product Hunt", "Hacker News", "Reddit", "LinkedIn"]),
      reflectionQuestion: "What needs to be perfect before you launch?",
      outcome: "A complete pre-launch checklist with all tasks and platform strategy defined",
      xpReward: 100,
    },
    {
      day: 29,
      title: "Marketing Content",
      description: "AI writes launch announcement content",
      phase: "Product Creator",
      videoUrl: null,
      aiTaskType: "template",
      aiTaskTitle: "Launch Content Pack",
      aiTaskDescription: "AI generates social posts, Product Hunt description, and announcement email.",
      suggestions: null,
      template: null,
      microDecisionQuestion: "Marketing angle?",
      microDecisionOptions: JSON.stringify(["Problem-focused", "Solution-focused", "Story-focused", "Feature-focused"]),
      reflectionQuestion: "What makes your product worth sharing?",
      outcome: "Launch content ready: social posts, Product Hunt copy, and announcement emails",
      xpReward: 100,
    },

    // PHASE 7: The Finisher (Day 30)
    {
      day: 30,
      title: "Launch Day!",
      description: "You did it! Launch your MVP to the world",
      phase: "The Finisher",
      videoUrl: null,
      aiTaskType: "setup",
      aiTaskTitle: "Final Launch Sequence",
      aiTaskDescription: "Today you launch! AI helps with deployment checklist and post-launch monitoring.",
      suggestions: null,
      template: null,
      microDecisionQuestion: "Launch feeling?",
      microDecisionOptions: JSON.stringify(["Excited", "Nervous", "Confident", "All of the above!"]),
      reflectionQuestion: "What did you learn most during this 30-day journey? What's next?",
      outcome: "Your SaaS MVP is live and available to the world!",
      xpReward: 300,
    },
  ];

  for (const day of dayContentData) {
    await db.insert(dayContent).values(day).onConflictDoUpdate({
      target: dayContent.day,
      set: {
        title: day.title,
        description: day.description,
        phase: day.phase,
        videoUrl: day.videoUrl,
        aiTaskType: day.aiTaskType,
        aiTaskTitle: day.aiTaskTitle,
        aiTaskDescription: day.aiTaskDescription,
        suggestions: day.suggestions,
        template: day.template,
        microDecisionQuestion: day.microDecisionQuestion,
        microDecisionOptions: day.microDecisionOptions,
        reflectionQuestion: day.reflectionQuestion,
        tip: day.tip,
        lesson: day.lesson,
        outcome: day.outcome,
        estimatedMinutes: day.estimatedMinutes,
        xpReward: day.xpReward,
        updatedAt: new Date(),
      },
    });
  }

  console.log("✅ Seeding complete!");
  process.exit(0);
}

seed().catch((error) => {
  console.error("❌ Seeding failed:", error);
  process.exit(1);
});
